<?xml version="1.0"?>
<package format="3">
  <name>mrs_uav_path_loader</name>
  <version>2.0.0</version>
  <description>Ported path loader component for ROS 2</description>
  <maintainer email="tsoyartem30@gmail.com">Artyom Tsoy</maintainer>
  <license>BSD 3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>mrs_msgs</depend>
  <depend>eigen3_cmake_module</depend>
  <depend>mrs_lib</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
